name: micro_commons_depends
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.0.3
  responsive_mobile: ^1.0.8
  intl: ^0.18.0
  dio: ^5.2.1+1
  uuid: ^3.0.4
  get: ^4.6.5
  get_it: ^7.6.0
  bloc: ^8.1.0
  mask_input_formatter: ^0.0.3
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.1.0
  flutter_holo_date_picker: ^1.1.0
  firebase_performance: ^0.9.2+3
  flutter_holo_date_picker_widget: ^1.1.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.1
  firebase_auth: ^4.6.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  # camera_web: ^0.3.2+1
  # camera: ^0.10.5+3
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.1.0
  sms_otp_auto_verify: ^2.1.0
  shimmer: ^2.0.0
  encrypt:
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.2.0
  qr_flutter: 
  share_plus: ^7.0.2
  widgets_to_image: ^0.0.2
  share_files_and_screenshot_widgets: ^1.0.6
  universal_html: ^2.2.2
  draggable_bottom_sheet: ^1.0.2
  slider_button: ^2.0.0
  flutter_svg: ^1.1.6
  flutter_masked_text2: ^0.9.1
  jsqr: ^0.1.1
  firebase_remote_config: ^4.2.6
  firebase_analytics:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
